/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                primary:              'var(--color-primary)',
                'primary-light':      'var(--color-primary-light)',
                'primary-text':       'var(--color-primary-text)',
                'primary-hover':      'var(--color-primary-hover)',
                'primary-subtle':     'var(--color-primary-subtle)',
                surface:              'var(--color-surface)',
                'surface-raised':     'var(--color-surface-raised)',
                'surface-overlay':    'var(--color-surface-overlay)',
                'surface-subtle':     'var(--color-surface-subtle)',
                'on-surface':         'var(--color-on-surface)',
                'on-surface-body':    'var(--color-on-surface-body)',
                'on-surface-muted':   'var(--color-on-surface-muted)',
                border:               'var(--color-border)',
                'border-mid':         'var(--color-border-mid)',
                'border-focus':       'var(--color-border-focus)',
                error:                'var(--color-error)',
                'on-error':           'var(--color-on-error)',
                success:              'var(--color-success)',
                'on-success':         'var(--color-on-success)',
                warning:              'var(--color-warning)',
                'on-warning':         'var(--color-on-warning)',
            },
            borderRadius: {
                none: 'var(--radius-none)',
                xs:   'var(--radius-xs)',
                sm:   'var(--radius-sm)',
                md:   'var(--radius-md)',
                lg:   'var(--radius-lg)',
                xl:   'var(--radius-xl)',
                '2xl':'var(--radius-2xl)',
                full: 'var(--radius-full)',
            },
            spacing: {
                1:  'var(--space-1)',
                2:  'var(--space-2)',
                3:  'var(--space-3)',
                4:  'var(--space-4)',
                5:  'var(--space-5)',
                6:  'var(--space-6)',
                7:  'var(--space-7)',
                8:  'var(--space-8)',
                10: 'var(--space-10)',
                12: 'var(--space-12)',
                14: 'var(--space-14)',
                16: 'var(--space-16)',
                20: 'var(--space-20)',
                24: 'var(--space-24)',
            },
            fontFamily: {
                display: ['var(--font-schmaltzy)', 'Palatino Linotype', 'serif'],
                heading: ['var(--font-fraunces)', 'Georgia', 'serif'],
                sans:    ['var(--font-nunito-sans)', 'Helvetica Neue', 'sans-serif'],
            },
            maxWidth: {
                prose: 'var(--layout-content-max-width)',
                page:  'var(--layout-page-max-width)',
            },
            boxShadow: {
                sm:          '0 2px 8px rgba(14,23,32,0.08), 0 0 1px rgba(14,23,32,0.06)',
                lg:          '0 8px 32px rgba(14,23,32,0.14), 0 2px 8px rgba(14,23,32,0.07)',
                'focus-ring':'0 0 0 3px rgba(22,131,255,0.18)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to:   { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to:   { height: '0' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up':   'accordion-up 0.2s ease-out',
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
}
