const caseStudies = [
    {
        private: false,
        homepage: true,
        company: 'Salesforce',
        title: 'Planning Better Together',
        subtitle: 'Scenario Planning for Everyone',
        description: 'Leading design for a new scenario planning product at Tableau. I designed visual modeling tools and collaborative comparison features that made building and experimenting with spreadsheet-based planning models more accessible, bringing decision-makers into what was once isolated work.',
        shortBlurb: 'Designing Tableau\'s scenario planning product from early concept through announcement.I created visual modeling interfaces and collaborative comparison tools that democratized spreadsheet- based planning for analysts and decision - makers.',
        href: '/work/scenario-planning',
        color1: 'sunglow',
        color2: 'sunset-red',
        imageSharp: '/work/thumbnails/scenario-sharp.png',
        imageBlurred: '/work/thumbnails/scenario-blurred.png',
    },
    {
        private: false,
        homepage: false,
        company: 'Personal Project',
        title: 'Sistema',
        subtitle: 'A Playbook for AI-Assisted Design Systems Work',
        description: 'Building a knowledge base and playbook tool that gives AI agents access to curated documentation from real design systems before generating. I designed and built the full product using Claude Code, then used it to design itself.',
        shortBlurb: 'Building a knowledge base and playbook tool for AI-assisted design systems work. Sistema grounds agent generation in real reference material from Material, Carbon, Atlassian, and more — so outputs reflect genuine design intent, not statistical averages.',
        href: '/work/sistema',
        color1: 'navy-blue',
        color2: 'caribbean-green',
        imageSharp: '/work/sistema/sistema-thumb.png',
        imageBlurred: '/work/sistema/sistema-thumb.png',
    },
    {
        private: false,
        homepage: false,
        company: 'ReflexAI',
        title: 'Building Prepare',
        subtitle: 'Design Practice at Startup Velocity',
        description: 'Establishing design practice at a fast-growing AI startup. As founding product designer, I built the design system and led three major product transformations—voice simulations, self-serve creation tools, and AI-generation—while growing the team from one designer to three.',
        shortBlurb: 'Founding the design practice at ReflexAI and leading product transformation. I established our design system and shipped voice training, self-serve scenario creation, and AI-generation features at startup velocity over 18 months.',
        href: '/work/prepare',
        color1: 'caribbean-green',
        color2: 'navy-blue',
        imageSharp: '/work/thumbnails/prepare-sharp.png',
        imageBlurred: '/work/thumbnails/prepare-blurred.png',
    },
    {
        private: false,
        homepage: false,
        company: 'ReflexAI',
        title: 'Forma',
        subtitle: 'A Design System at the Speed of Startup',
        description: 'Building a design system for a fast-growing startup. I founded the component library, advocated for organizational investment, and led cross-functional work to create a fully documented system with 20+ components—enabling rapid feature development while scaling the design team from one to three.',
        shortBlurb: 'Creating a design system at startup velocity. I founded Forma\'s component library, earned organizational buy -in, and led cross - functional development of a documented system that enabled consistent, rapid product evolution while the company doubled in size.',
        href: '/work/forma',
        color1: 'navy-blue',
        color2: 'purple-heart',
        imageSharp: '/work/thumbnails/forma-sharp.png',
        imageBlurred: '/work/thumbnails/forma-blurred.png',
    },
    {
        private: false,
        homepage: false,
        company: 'Figma Plugin',
        title: 'A Refined Palette',
        subtitle: 'Systematic Color for Design Systems',
        description: 'Creating a color palette generator to accelerate design system adoption. I coded an internal tool that generates accessible, flexible color palettes from seed colors—helping teams move faster and maintain consistency. Later released as Paletteer, a Figma plugin with 10,000+ users.',
        shortBlurb: 'Building a color palette generator that creates accessible design tokens from seed colors. Started as an internal tool to speed design system work, then released as Paletteer—a Figma plugin now used by 10,000+ designers.',
        href: '/work/colors',
        color1: 'purple-heart',
        color2: 'navy-blue',
        imageSharp: '/work/thumbnails/paletteer-sharp.png',
        imageBlurred: '/work/thumbnails/paletteer-blurred.png',
    },
];

export default caseStudies;
