import _ from 'lodash'
import Head from 'next/head'

import ArtboardContainer from '../components/ArtboardContainer'
import Layout from '../components/Layout'

export default function Home() {
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <ArtboardContainer />
        </Layout>
    )
}
